[package]
name = "conceal"
version = "0.4.1"
authors = ["Collide <three-dim-sky@foxmail.com>"]
edition = "2021"
description = "Command line recycle bin"
documentation = "https://github.com/TD-Sky/conceal"
repository = "https://github.com/TD-Sky/conceal"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["trash", "remove", "recycle", "freedesktop"]
license = "MIT"

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
dirs = "5.0"
owo-colors = "3.5"
thiserror = "1"
trash = { git = "https://github.com/Byron/trash-rs" }
chrono = "0.4"

[build-dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
clap_complete = "4.4"
clap_complete_nushell = "4.4"

[profile.release]
lto = true
strip = true
